### ISSUE TITLE
Add lock file?

### ISSUE THREAD

**Issue by eight04** [eight04/vpip#3]
Every time `pylint` updates `astroid`, the CI build failed. It is pretty annoying.

If we use `requirements.txt` to pin all packages, where should we store dev dependencies?

**Comment by eight04** [comment]
Maybe with the name `requirements-lock.txt` so it is compatible with the current design.

**Comment by jayvdb** [comment]
A lock file sounds good.  I've been doing a bit of a round-up of lock-type tools at https://github.com/storyscript/community/issues/7 .  Need to finish analysis of @PyScaffold , which I noticed your dependency `ConfigUpdater` is part of.
