### ISSUE TITLE
pip will install packages to user site by default

### ISSUE THREAD

**Issue by eight04** [eight04/vpip#4]
https://github.com/pypa/pip/issues/1668
https://github.com/pypa/pip/pull/7002
Investigate how does it work with venv.

**Comment by takluyver** [comment]
It should still work as before with a venv - it will only do a user install if it doesn't have write access to the `site-packages` directory where a normal install would go. And only if `site.ENABLE_USER_SITE` is true as well.

**Comment by eight04** [comment]
It seems that the Python installer doesn't add user-site to %PATH% if you selected `Install for all users` (which installs python to `program files`).

As the result, even if [the link success](https://github.com/eight04/vpip/blob/ad6bc73ab91c2de0f180fc06eadda9b4bb21427d/vpip/venv.py#L35), the user still can't access the CLI.

Windows 10 64bit
Python 3.8.1 32bit
